### ISSUE TITLE
Hide particles and sound

### ISSUE THREAD

**Issue by Slend32** [Artificial-720/burning-daylight#9]
Hey! Your plugin is very good, but can you add way to hide particles and sound of fire in config?

**Comment by artificial-720** [comment]
Released v1.3.0 to add this setting.
Set these settings to false to disable particles and fire sounds caused by this plugin.

```yaml
effects:
  visuals: false
  sounds: false
```
